Add build instructions for Windows
procxx/tdesktop pull request #63
Opened 2018-01-13 06:36 UTC by ForNeVeR

Part of #45.

2018-01-13 06:49 UTC, crackedmind commented
:white_check_mark: [Build kepka 1.0.46-iolevqly completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.46-iolevqly) (commit https://github.com/procxx/kepka/commit/cdaca2fd03 by @ForNeVeR)

2018-01-13 07:45 UTC, berkus submitted a review, later dismissed

2018-01-13 08:01 UTC, crackedmind commented
:white_check_mark: [Build kepka 1.0.46-octyqrto completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.46-octyqrto) (commit https://github.com/procxx/kepka/commit/741fa92ef1 by @ForNeVeR)

2018-01-13 08:10 UTC, berkus requested changes

2018-01-13 08:10 UTC, berkus commented on README.md
> +or later and [Visual Studio][visual-studio] 2017 or later, and set the following
Could we remove unnecessary linebreaks here (1)

2018-01-13 08:10 UTC, berkus commented on README.md
> +command prompt:
And here (2) ^

2018-01-13 08:14 UTC, berkus submitted a review, later dismissed

2018-01-13 08:26 UTC, crackedmind commented
:white_check_mark: [Build kepka 1.0.46-alacxeen completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.46-alacxeen) (commit https://github.com/procxx/kepka/commit/8d205d57e4 by @ForNeVeR)

2018-01-13 19:41 UTC, crackedmind submitted a review, later dismissed

2018-01-14 00:02 UTC, crackedmind commented
:white_check_mark: [Build kepka 1.0.47-fmodwarp completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.47-fmodwarp) (commit https://github.com/procxx/kepka/commit/9b7aaef576 by @berkus)

2018-01-14 03:52 UTC, crackedmind commented
:white_check_mark: [Build kepka 1.0.47-betivnlc completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.47-betivnlc) (commit https://github.com/procxx/kepka/commit/d2943a89c2 by @ForNeVeR)

2018-01-15 10:49 UTC, crackedmind commented
:white_check_mark: [Build kepka 1.0.48-msouckbq completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.48-msouckbq) (commit https://github.com/procxx/kepka/commit/2cbfefcd58 by @ForNeVeR)

2018-01-15 11:45 UTC, merged