[Mac OS] add support native OpenAl for mac os
procxx/tdesktop pull request #85
Opened 2018-01-17 22:25 UTC by pperehozhih

(need add cmake arg PROCXX_USE_NATIVE_OPEN_AL)

2018-01-17 23:28 UTC, crackedmind commented
:white_check_mark: [Build kepka 1.0.57-fclmtcst completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.57-fclmtcst) (commit https://github.com/procxx/kepka/commit/2bc2cc55e1 by @pperehozhih)

2018-01-18 05:29 UTC, ForNeVeR commented on Telegram/SourceFiles/media/media_defs.h
> +the unofficial desktop version of Telegram messaging app, see https://procxx.github.io/
`the` → `an`? *!!*

2018-01-18 05:30 UTC, ForNeVeR commented on Telegram/SourceFiles/media/media_defs.h
> +Telegram Desktop is free software: you can redistribute it and/or modify
`Telegram Desktop` → `Kepka`

2018-01-18 19:22 UTC, crackedmind commented
:white_check_mark: [Build kepka 1.0.59-yhoimuro completed](https://ci.appveyor.com/project/procxx/tdesktop/build/1.0.59-yhoimuro) (commit https://github.com/procxx/kepka/commit/d16c41963c by @pperehozhih)

2018-01-18 20:07 UTC, zamazan4ik approved these changes

2018-01-19 08:50 UTC, berkus requested changes

2018-01-19 08:50 UTC, berkus commented on Telegram/SourceFiles/media/media_defs.h
> +
Remove empty line 1

2018-01-19 08:50 UTC, berkus commented on CMakeLists.txt
> +    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -framework OpenAL")
This is a wrong location, should be in Telegram/CMakeLists.txt where all frameworks are added.

2018-01-19 08:50 UTC, berkus commented on Telegram/CMakeLists.txt
> +    if (PROCXX_USE_NATIVE_OPEN_AL_MAC)
drop PROCXX_USE_NATIVE_OPEN_AL_MAC check, use native OpenAL on mac unconditionally.

2018-01-19 08:50 UTC, berkus commented on Telegram/CMakeLists.txt
> +        add_definitions(-DPROCXX_USE_NATIVE_OPEN_AL_MAC)
Use `target_compile_definitions()` instead below in the target section

2018-01-19 08:52 UTC, berkus commented
Based on the discussion and usage of ALC_CONNECTED in Kepka sources (which is not supported by MacOS OpenAL) I am not sure this PR can be merged as-is - it will probably break device disconnection scenarios.

The only reason proposed for this PR is "less dependencies" but on mac `brew install openal-soft` is the simplest method to obtain the dependency so I don't see it as a problem. Conan packages also have some openal-soft builds.

2018-04-22 16:46 UTC, berkus commented
Lets close this for now, as there seem to be no acceptable changes to do.

2018-04-22 16:46 UTC, closed without merging